swagger: "2.0"
info:
  title: Likes API
  description: API for liking posts and comments
  version: "1.0"

basePath: /service
schemes:
  - http

definitions:
  LikeObject:
    type: object
    properties:
      "@context":
        type: string
        description: The context of the like object.
      summary:
        type: string
        description: A summary of the like.
      type:
        type: string
        description: The type of the like object.
      author:
        $ref: '#/definitions/Author'
      object:
        type: string
        description: The URL of the object being liked.

  LikeList:
    type: object
    properties:
      type:
        type: string
        description: The type of the like list object.
      items:
        type: array
        items:
          $ref: '#/definitions/LikeObject'

  Author:
    type: object
    properties:
      type:
        type: string
        description: Type of the author.
      id:
        type: string
        description: ID of the author.
      host:
        type: string
        description: Host of the author.
      displayName:
        type: string
        description: Display name of the author.
      url:
        type: string
        description: URL of the author.
      github:
        type: string
        description: GitHub URL of the author.
      profileImage:
        type: string
        description: URL of the author's profile image.

paths:
  /authors/{author_id}/inbox/:
    post:
      summary: Send a like object to the inbox of the author with ID author_id.
      parameters:
        - name: author_id
          in: path
          required: true
          description: ID of the author to send the like to.
          type: string
        - name: like_object
          in: body
          required: true
          description: Like object to send.
          schema:
            $ref: '#/definitions/LikeObject'
      responses:
        200:
          description: Like object sent successfully.

  /authors/{author_id}/posts/{post_id}/likes:
    get:
      summary: Get a list of likes from other authors on the post with ID post_id by the author with ID author_id.
      parameters:
        - name: author_id
          in: path
          required: true
          description: ID of the author who created the post.
          type: string
        - name: post_id
          in: path
          required: true
          description: ID of the post to get likes for.
          type: string
      responses:
        200:
          description: List of likes retrieved successfully.
          schema:
            $ref: '#/definitions/LikeList'

    post:
      summary: Like the post with ID post_id by the author with ID author_id.
      parameters:
        - name: author_id
          in: path
          required: true
          description: ID of the author who is liking the post.
          type: string
        - name: post_id
          in: path
          required: true
          description: ID of the post to like.
          type: string
        - name: like_object
          in: body
          required: true
          description: Like object to send.
          schema:
            $ref: '#/definitions/LikeObject'
      responses:
        200:
          description: Post liked successfully.

